
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 18/08/2009 - 09:55 p.m.
// This is a partial class file. The other one is ClasificacionOrganizacionMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class ClasificacionOrganizacionMapper : BaseGateway<ClasificacionOrganizacion, ClasificacionOrganizacionList>, IGenericGateway
    {


        #region "Singleton"

        static ClasificacionOrganizacionMapper _instance;

        private ClasificacionOrganizacionMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static ClasificacionOrganizacionMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ClasificacionOrganizacionMapper();
                else {
                    ClasificacionOrganizacionMapper inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.ClasificacionOrganizacionMapperSingleton"] as ClasificacionOrganizacionMapper;
                    if (inst == null) {
                        inst = new ClasificacionOrganizacionMapper();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.ClasificacionOrganizacionMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(ClasificacionOrganizacion);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "ClasificacionOrganizacion"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(ClasificacionOrganizacionMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ClasificacionOrganizacion entity)
        {
            
            IMappeableClasificacionOrganizacionObject ClasificacionOrganizacion = (IMappeableClasificacionOrganizacionObject)entity;
            ClasificacionOrganizacion.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? "" : reader.GetString(1));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(ClasificacionOrganizacion entity)
        {

            IMappeableClasificacionOrganizacionObject ClasificacionOrganizacion = (IMappeableClasificacionOrganizacionObject)entity;
            return ClasificacionOrganizacion.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(ClasificacionOrganizacion entity)
        {

            IMappeableClasificacionOrganizacionObject ClasificacionOrganizacion = (IMappeableClasificacionOrganizacionObject)entity;
            return ClasificacionOrganizacion.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(ClasificacionOrganizacion entity)
        {

            IMappeableClasificacionOrganizacionObject ClasificacionOrganizacion = (IMappeableClasificacionOrganizacionObject)entity;
            return ClasificacionOrganizacion.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ClasificacionOrganizacion entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableClasificacionOrganizacionObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(ClasificacionOrganizacion entity)
        {
            
            ((IMappeableClasificacionOrganizacion)entity).CompleteEntity();
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a ClasificacionOrganizacion by execute a SQL Query Text
        /// </summary>
        public ClasificacionOrganizacion GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ClasificacionOrganizacionList by execute a SQL Query Text
        /// </summary>
        public ClasificacionOrganizacionList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public ClasificacionOrganizacion GetOne(System.Int32 Clave)
        {
            return base.GetOne(new ClasificacionOrganizacion(Clave));
        }


        // GetOne By Objects and Params
            


        


        

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ClasificacionOrganizacion_Delete", Clave);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ClasificacionOrganizacion_Delete", Clave);
        }


        // Delete By Objects and Params
            



        


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class ClasificacionOrganizacionMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.ClasificacionOrganizacionMapper Instance()
        {
            return BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.ClasificacionOrganizacionMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a ClasificacionOrganizacionEntity by calling a Stored Procedure
        /// </summary>
        public Entities.ClasificacionOrganizacion GetOne(System.Int32 Clave) {
            return Instance().GetOne( Clave);
        }

        // GetBy Objects and Params
            

        

       

        /// <summary>
        /// Delete children for ClasificacionOrganizacion
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, ClasificacionOrganizacion entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        
        /// <summary>
        /// Delete ClasificacionOrganizacion 
        /// </summary>
        public void Delete(System.Int32 Clave){
            Instance().Delete(Clave);
        }

        /// <summary>
        /// Delete ClasificacionOrganizacion 
        /// </summary>
        public void Delete(Entities.ClasificacionOrganizacion entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save ClasificacionOrganizacion  
        /// </summary>
        public void Save(Entities.ClasificacionOrganizacion entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert ClasificacionOrganizacion 
        /// </summary>
        public void Insert(Entities.ClasificacionOrganizacion entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll ClasificacionOrganizacion 
        /// </summary>
        public Entities.ClasificacionOrganizacionList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save ClasificacionOrganizacion 
        /// </summary>
        public void Save(System.Int32 Clave, System.String Descripcion){
            Entities.ClasificacionOrganizacion entity = Instance().GetOne(Clave);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "Clave", Clave));

            entity.Descripcion = Descripcion;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert ClasificacionOrganizacion
        /// </summary>
        public void Insert(System.String Descripcion){
            Entities.ClasificacionOrganizacion entity = new Entities.ClasificacionOrganizacion();

            entity.Descripcion = Descripcion;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class ClasificacionOrganizacionLoader<T> : BaseLoader< T, ClasificacionOrganizacion, ObjectList<T>>, IGenericGateway where T : ClasificacionOrganizacion, new()
    {

        #region "Singleton"

        static ClasificacionOrganizacionLoader<T> _instance;

        private ClasificacionOrganizacionLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static ClasificacionOrganizacionLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ClasificacionOrganizacionLoader<T>();
                else {
                    ClasificacionOrganizacionLoader<T> inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.ClasificacionOrganizacionLoaderSingleton"] as ClasificacionOrganizacionLoader<T>;
                    if (inst == null) {
                        inst = new ClasificacionOrganizacionLoader<T>();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.ClasificacionOrganizacionLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(ClasificacionOrganizacion);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "ClasificacionOrganizacion"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ClasificacionOrganizacion entity)
        {
            
            IMappeableClasificacionOrganizacionObject ClasificacionOrganizacion = (IMappeableClasificacionOrganizacionObject)entity;
            ClasificacionOrganizacion.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? "" : reader.GetString(1));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            
            ((IMappeableClasificacionOrganizacion)entity).CompleteEntity();
        }


        



        /// <summary>
        /// Get a ClasificacionOrganizacion by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ClasificacionOrganizacionList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 Clave)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "ClasificacionOrganizacion_GetOne", Clave);
        }


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





