
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 8/30/2009 - 1:47 PM
// This is a partial class file. The other one is RoboVehiculoAccesoriosMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class RoboVehiculoAccesoriosMapper : BaseGateway<RoboVehiculoAccesorios, RoboVehiculoAccesoriosList>, IGenericGateway
    {


        #region "Singleton"

        static RoboVehiculoAccesoriosMapper _instance;

        private RoboVehiculoAccesoriosMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static RoboVehiculoAccesoriosMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new RoboVehiculoAccesoriosMapper();
                else {
                    RoboVehiculoAccesoriosMapper inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.RoboVehiculoAccesoriosMapperSingleton"] as RoboVehiculoAccesoriosMapper;
                    if (inst == null) {
                        inst = new RoboVehiculoAccesoriosMapper();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.RoboVehiculoAccesoriosMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdAccesorio"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(RoboVehiculoAccesorios);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "RoboVehiculoAccesorios"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(RoboVehiculoAccesoriosMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, RoboVehiculoAccesorios entity)
        {
            
            IMappeableRoboVehiculoAccesoriosObject RoboVehiculoAccesorios = (IMappeableRoboVehiculoAccesoriosObject)entity;
            RoboVehiculoAccesorios.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? new System.Nullable<System.Int32>() : reader.GetInt32(1),
reader.GetString(2),
reader.GetInt32(3));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(RoboVehiculoAccesorios entity)
        {

            IMappeableRoboVehiculoAccesoriosObject RoboVehiculoAccesorios = (IMappeableRoboVehiculoAccesoriosObject)entity;
            return RoboVehiculoAccesorios.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(RoboVehiculoAccesorios entity)
        {

            IMappeableRoboVehiculoAccesoriosObject RoboVehiculoAccesorios = (IMappeableRoboVehiculoAccesoriosObject)entity;
            return RoboVehiculoAccesorios.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(RoboVehiculoAccesorios entity)
        {

            IMappeableRoboVehiculoAccesoriosObject RoboVehiculoAccesorios = (IMappeableRoboVehiculoAccesoriosObject)entity;
            return RoboVehiculoAccesorios.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(RoboVehiculoAccesorios entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableRoboVehiculoAccesoriosObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "rb_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(RoboVehiculoAccesorios entity)
        {
            Objects.RoboAccesoriosObject RoboAccesoriosEntity = null; // Lazy load
Objects.VehiculoObject VehiculoEntity = null; // Lazy load
            ((IMappeableRoboVehiculoAccesorios)entity).CompleteEntity(RoboAccesoriosEntity, VehiculoEntity);
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a RoboVehiculoAccesorios by execute a SQL Query Text
        /// </summary>
        public RoboVehiculoAccesorios GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a RoboVehiculoAccesoriosList by execute a SQL Query Text
        /// </summary>
        public RoboVehiculoAccesoriosList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesorios GetOne(System.Int32 IdAccesorio)
        {
            return base.GetOne(new RoboVehiculoAccesorios(IdAccesorio));
        }


        // GetOne By Objects and Params
            


        

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByRoboAccesorios(DbTransaction transaction, System.Int32 IdRoboAccesorio)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", IdRoboAccesorio);
        }

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByRoboAccesorios(DbTransaction transaction, IUniqueIdentifiable RoboAccesorios)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", RoboAccesorios.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByVehiculo(DbTransaction transaction, System.Int32 ClaveVehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", ClaveVehiculo);
        }

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByVehiculo(DbTransaction transaction, IUniqueIdentifiable Vehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", Vehiculo.Identifier());
        }

    


        

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByRoboAccesorios(System.Int32 IdRoboAccesorio)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", IdRoboAccesorio);
        }

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByRoboAccesorios(IUniqueIdentifiable RoboAccesorios)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", RoboAccesorios.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByVehiculo(System.Int32 ClaveVehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", ClaveVehiculo);
        }

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosList GetByVehiculo(IUniqueIdentifiable Vehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", Vehiculo.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 IdAccesorio)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_Delete", IdAccesorio);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdAccesorio)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_Delete", IdAccesorio);
        }


        // Delete By Objects and Params
            



        

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByRoboAccesorios(System.Int32 IdRoboAccesorio)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByRoboAccesorios", IdRoboAccesorio);
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByRoboAccesorios(DbTransaction transaction, System.Int32 IdRoboAccesorio)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByRoboAccesorios", IdRoboAccesorio);
        }


        /// <summary>
        /// 
        /// </summary>
        public void DeleteByRoboAccesorios(IUniqueIdentifiable RoboAccesorios)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByRoboAccesorios", RoboAccesorios.Identifier());
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByRoboAccesorios(DbTransaction transaction, IUniqueIdentifiable RoboAccesorios)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByRoboAccesorios", RoboAccesorios.Identifier());
        }


    

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByVehiculo(System.Int32 ClaveVehiculo)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByVehiculo", ClaveVehiculo);
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByVehiculo(DbTransaction transaction, System.Int32 ClaveVehiculo)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByVehiculo", ClaveVehiculo);
        }


        /// <summary>
        /// 
        /// </summary>
        public void DeleteByVehiculo(IUniqueIdentifiable Vehiculo)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByVehiculo", Vehiculo.Identifier());
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByVehiculo(DbTransaction transaction, IUniqueIdentifiable Vehiculo)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_DeleteByVehiculo", Vehiculo.Identifier());
        }


    


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class RoboVehiculoAccesoriosMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.RoboVehiculoAccesoriosMapper Instance()
        {
            return BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.RoboVehiculoAccesoriosMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a RoboVehiculoAccesoriosEntity by calling a Stored Procedure
        /// </summary>
        public Entities.RoboVehiculoAccesorios GetOne(System.Int32 IdAccesorio) {
            return Instance().GetOne( IdAccesorio);
        }

        // GetBy Objects and Params
            

        

        /// <summary>
        /// Get a RoboVehiculoAccesoriosList by calling a Stored Procedure
        /// </summary>
        public Entities.RoboVehiculoAccesoriosList GetByRoboAccesorios(System.Int32 IdRoboAccesorio)
        {
            return Instance().GetByRoboAccesorios(IdRoboAccesorio);
        }

        /// <summary>
        /// Get a RoboVehiculoAccesoriosList by calling a Stored Procedure
        /// </summary>
        public Entities.RoboVehiculoAccesoriosList GetByRoboAccesorios(IUniqueIdentifiable RoboAccesorios)
        {
            return Instance().GetByRoboAccesorios(RoboAccesorios);
        }

    

        /// <summary>
        /// Get a RoboVehiculoAccesoriosList by calling a Stored Procedure
        /// </summary>
        public Entities.RoboVehiculoAccesoriosList GetByVehiculo(System.Int32 ClaveVehiculo)
        {
            return Instance().GetByVehiculo(ClaveVehiculo);
        }

        /// <summary>
        /// Get a RoboVehiculoAccesoriosList by calling a Stored Procedure
        /// </summary>
        public Entities.RoboVehiculoAccesoriosList GetByVehiculo(IUniqueIdentifiable Vehiculo)
        {
            return Instance().GetByVehiculo(Vehiculo);
        }

    

       

        /// <summary>
        /// Delete children for RoboVehiculoAccesorios
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, RoboVehiculoAccesorios entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        

        /// <summary>
        /// Delete RoboVehiculoAccesorios by RoboAccesorios
        /// </summary>
        public void DeleteByRoboAccesorios(System.Int32 IdRoboAccesorio)
        {
            Instance().DeleteByRoboAccesorios(IdRoboAccesorio);
        }

        /// <summary>
        /// Delete RoboVehiculoAccesorios by RoboAccesorios
        /// </summary>
        public void DeleteByRoboAccesorios(IUniqueIdentifiable RoboAccesorios)
        {
            Instance().DeleteByRoboAccesorios(RoboAccesorios);
        }

    

        /// <summary>
        /// Delete RoboVehiculoAccesorios by Vehiculo
        /// </summary>
        public void DeleteByVehiculo(System.Int32 ClaveVehiculo)
        {
            Instance().DeleteByVehiculo(ClaveVehiculo);
        }

        /// <summary>
        /// Delete RoboVehiculoAccesorios by Vehiculo
        /// </summary>
        public void DeleteByVehiculo(IUniqueIdentifiable Vehiculo)
        {
            Instance().DeleteByVehiculo(Vehiculo);
        }

    
        /// <summary>
        /// Delete RoboVehiculoAccesorios 
        /// </summary>
        public void Delete(System.Int32 IdAccesorio){
            Instance().Delete(IdAccesorio);
        }

        /// <summary>
        /// Delete RoboVehiculoAccesorios 
        /// </summary>
        public void Delete(Entities.RoboVehiculoAccesorios entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save RoboVehiculoAccesorios  
        /// </summary>
        public void Save(Entities.RoboVehiculoAccesorios entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert RoboVehiculoAccesorios 
        /// </summary>
        public void Insert(Entities.RoboVehiculoAccesorios entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll RoboVehiculoAccesorios 
        /// </summary>
        public Entities.RoboVehiculoAccesoriosList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save RoboVehiculoAccesorios 
        /// </summary>
        public void Save(System.Int32 IdAccesorio, System.Int32 ClaveVehiculo, System.String AccesorioRobado, System.Int32 IdRoboAccesorio){
            Entities.RoboVehiculoAccesorios entity = Instance().GetOne(IdAccesorio);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "IdAccesorio", IdAccesorio));

            entity.ClaveVehiculo = ClaveVehiculo;
            entity.AccesorioRobado = AccesorioRobado;
            entity.IdRoboAccesorio = IdRoboAccesorio;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert RoboVehiculoAccesorios
        /// </summary>
        public void Insert(System.Int32 ClaveVehiculo, System.String AccesorioRobado, System.Int32 IdRoboAccesorio){
            Entities.RoboVehiculoAccesorios entity = new Entities.RoboVehiculoAccesorios();

            entity.ClaveVehiculo = ClaveVehiculo;
            entity.AccesorioRobado = AccesorioRobado;
            entity.IdRoboAccesorio = IdRoboAccesorio;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class RoboVehiculoAccesoriosLoader<T> : BaseLoader< T, RoboVehiculoAccesorios, ObjectList<T>>, IGenericGateway where T : RoboVehiculoAccesorios, new()
    {

        #region "Singleton"

        static RoboVehiculoAccesoriosLoader<T> _instance;

        private RoboVehiculoAccesoriosLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static RoboVehiculoAccesoriosLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new RoboVehiculoAccesoriosLoader<T>();
                else {
                    RoboVehiculoAccesoriosLoader<T> inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.RoboVehiculoAccesoriosLoaderSingleton"] as RoboVehiculoAccesoriosLoader<T>;
                    if (inst == null) {
                        inst = new RoboVehiculoAccesoriosLoader<T>();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.RoboVehiculoAccesoriosLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdAccesorio"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(RoboVehiculoAccesorios);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "RoboVehiculoAccesorios"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, RoboVehiculoAccesorios entity)
        {
            
            IMappeableRoboVehiculoAccesoriosObject RoboVehiculoAccesorios = (IMappeableRoboVehiculoAccesoriosObject)entity;
            RoboVehiculoAccesorios.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? new System.Nullable<System.Int32>() : reader.GetInt32(1),
reader.GetString(2),
reader.GetInt32(3));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "rb_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            Objects.RoboAccesoriosObject RoboAccesoriosEntity = null; // Lazy load
Objects.VehiculoObject VehiculoEntity = null; // Lazy load
            ((IMappeableRoboVehiculoAccesorios)entity).CompleteEntity(RoboAccesoriosEntity, VehiculoEntity);
        }


        



        /// <summary>
        /// Get a RoboVehiculoAccesorios by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a RoboVehiculoAccesoriosList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 IdAccesorio)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetOne", IdAccesorio);
        }


        // GetOne By Objects and Params
            


        

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByRoboAccesorios(DbTransaction transaction, System.Int32 IdRoboAccesorio)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", IdRoboAccesorio);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByRoboAccesorios(DbTransaction transaction, IUniqueIdentifiable RoboAccesorios)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", RoboAccesorios.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByVehiculo(DbTransaction transaction, System.Int32 ClaveVehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", ClaveVehiculo);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByVehiculo(DbTransaction transaction, IUniqueIdentifiable Vehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", Vehiculo.Identifier());
        }

    


        

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByRoboAccesorios(System.Int32 IdRoboAccesorio)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", IdRoboAccesorio);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByRoboAccesorios(IUniqueIdentifiable RoboAccesorios)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByRoboAccesorios", RoboAccesorios.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByVehiculo(System.Int32 ClaveVehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", ClaveVehiculo);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByVehiculo(IUniqueIdentifiable Vehiculo)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "RoboVehiculoAccesorios_GetByVehiculo", Vehiculo.Identifier());
        }

    

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





