
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 29/07/2009 - 02:18 p.m.
// This is a partial class file. The other one is UsuarioMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class UsuarioMapper : BaseGateway<Usuario, UsuarioList>, IGenericGateway
    {


        #region "Singleton"

        static UsuarioMapper _instance;

        private UsuarioMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static UsuarioMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new UsuarioMapper();
                else {
                    UsuarioMapper inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.UsuarioMapperSingleton"] as UsuarioMapper;
                    if (inst == null) {
                        inst = new UsuarioMapper();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.UsuarioMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(Usuario);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "Usuario"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(UsuarioMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, Usuario entity)
        {
            
            IMappeableUsuarioObject Usuario = (IMappeableUsuarioObject)entity;
            Usuario.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
(reader.IsDBNull(2)) ? "" : reader.GetString(2),
(reader.IsDBNull(3)) ? new System.Nullable<System.Boolean>() : reader.GetBoolean(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
(reader.IsDBNull(5)) ? new System.Nullable<System.Boolean>() : reader.GetBoolean(5));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(Usuario entity)
        {

            IMappeableUsuarioObject Usuario = (IMappeableUsuarioObject)entity;
            return Usuario.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(Usuario entity)
        {

            IMappeableUsuarioObject Usuario = (IMappeableUsuarioObject)entity;
            return Usuario.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(Usuario entity)
        {

            IMappeableUsuarioObject Usuario = (IMappeableUsuarioObject)entity;
            return Usuario.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(Usuario entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableUsuarioObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(Usuario entity)
        {
            
            ((IMappeableUsuario)entity).CompleteEntity();
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }




        /// <summary>
        /// Get a Usuario by execute a SQL Query Text
        /// </summary>
        public Usuario GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a UsuarioList by execute a SQL Query Text
        /// </summary>
        public UsuarioList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public Usuario GetOne(System.Int32 Clave)
        {
            return base.GetOne(new Usuario(Clave));
        }


        // GetOne By Objects and Params

        public Usuario GetByUsuario(System.String usuario)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "Usuario_GetByUsuario", usuario);
        }

        


        

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Usuario_Delete", Clave);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Usuario_Delete", Clave);
        }


        // Delete By Objects and Params
            



        


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class UsuarioMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.UsuarioMapper Instance()
        {
            return BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.UsuarioMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a UsuarioEntity by calling a Stored Procedure
        /// </summary>
        public Entities.Usuario GetOne(System.Int32 Clave) {
            return Instance().GetOne( Clave);
        }

        // GetBy Objects and Params
            

        

       

        /// <summary>
        /// Delete children for Usuario
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, Usuario entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        
        /// <summary>
        /// Delete Usuario 
        /// </summary>
        public void Delete(System.Int32 Clave){
            Instance().Delete(Clave);
        }

        /// <summary>
        /// Delete Usuario 
        /// </summary>
        public void Delete(Entities.Usuario entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save Usuario  
        /// </summary>
        public void Save(Entities.Usuario entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert Usuario 
        /// </summary>
        public void Insert(Entities.Usuario entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll Usuario 
        /// </summary>
        public Entities.UsuarioList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save Usuario 
        /// </summary>
        public void Save(System.Int32 Clave, System.String NombreUsuario, System.String NombrePropio, System.Boolean Activo, System.String Contraseña, System.Boolean Despachador){
            Entities.Usuario entity = Instance().GetOne(Clave);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "Clave", Clave));

            entity.NombreUsuario = NombreUsuario;
            entity.NombrePropio = NombrePropio;
            entity.Activo = Activo;
            entity.Contraseña = Contraseña;
            entity.Despachador = Despachador;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert Usuario
        /// </summary>
        public void Insert(System.String NombreUsuario, System.String NombrePropio, System.Boolean Activo, System.String Contraseña, System.Boolean Despachador){
            Entities.Usuario entity = new Entities.Usuario();

            entity.NombreUsuario = NombreUsuario;
            entity.NombrePropio = NombrePropio;
            entity.Activo = Activo;
            entity.Contraseña = Contraseña;
            entity.Despachador = Despachador;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class UsuarioLoader<T> : BaseLoader< T, Usuario, ObjectList<T>>, IGenericGateway where T : Usuario, new()
    {

        #region "Singleton"

        static UsuarioLoader<T> _instance;

        private UsuarioLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static UsuarioLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new UsuarioLoader<T>();
                else {
                    UsuarioLoader<T> inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.UsuarioLoaderSingleton"] as UsuarioLoader<T>;
                    if (inst == null) {
                        inst = new UsuarioLoader<T>();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.UsuarioLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(Usuario);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "Usuario"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, Usuario entity)
        {
            
            IMappeableUsuarioObject Usuario = (IMappeableUsuarioObject)entity;
            Usuario.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
(reader.IsDBNull(2)) ? "" : reader.GetString(2),
(reader.IsDBNull(3)) ? new System.Nullable<System.Boolean>() : reader.GetBoolean(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
(reader.IsDBNull(5)) ? new System.Nullable<System.Boolean>() : reader.GetBoolean(5));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            
            ((IMappeableUsuario)entity).CompleteEntity();
        }


        



        /// <summary>
        /// Get a Usuario by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a UsuarioList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 Clave)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "Usuario_GetOne", Clave);
        }


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





