
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 28/07/2009 - 08:51 p.m.
// This is a partial class file. The other one is EstatusIncidenciaMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class EstatusIncidenciaMapper : BaseGateway<EstatusIncidenciaObject, EstatusIncidenciaObjectList>, IGenericGateway
    {


        #region "Singleton"

        static EstatusIncidenciaMapper _instance;

        private EstatusIncidenciaMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static EstatusIncidenciaMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new EstatusIncidenciaMapper();
                else {
                    EstatusIncidenciaMapper inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.EstatusIncidenciaMapperSingleton"] as EstatusIncidenciaMapper;
                    if (inst == null) {
                        inst = new EstatusIncidenciaMapper();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.EstatusIncidenciaMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(EstatusIncidenciaObject);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "EstatusIncidencia"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(EstatusIncidenciaMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, EstatusIncidenciaObject entity)
        {
            
            IMappeableEstatusIncidenciaObject EstatusIncidencia = (IMappeableEstatusIncidenciaObject)entity;
            EstatusIncidencia.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? "" : reader.GetString(1));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(EstatusIncidenciaObject entity)
        {

            IMappeableEstatusIncidenciaObject EstatusIncidencia = (IMappeableEstatusIncidenciaObject)entity;
            return EstatusIncidencia.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(EstatusIncidenciaObject entity)
        {

            IMappeableEstatusIncidenciaObject EstatusIncidencia = (IMappeableEstatusIncidenciaObject)entity;
            return EstatusIncidencia.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(EstatusIncidenciaObject entity)
        {

            IMappeableEstatusIncidenciaObject EstatusIncidencia = (IMappeableEstatusIncidenciaObject)entity;
            return EstatusIncidencia.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(EstatusIncidenciaObject entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableEstatusIncidenciaObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


          





        /// <summary>
        /// Get a EstatusIncidenciaObject by execute a SQL Query Text
        /// </summary>
        public EstatusIncidenciaObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a EstatusIncidenciaObjectList by execute a SQL Query Text
        /// </summary>
        public EstatusIncidenciaObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public EstatusIncidenciaObject GetOne(System.Int32 Clave)
        {
            return base.GetOne(new EstatusIncidenciaObject(Clave));
        }


        // GetOne By Objects and Params
            


        


        

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "EstatusIncidencia_Delete", Clave);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "EstatusIncidencia_Delete", Clave);
        }


        // Delete By Objects and Params
            



        


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class EstatusIncidenciaMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.EstatusIncidenciaMapper Instance()
        {
            return BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.EstatusIncidenciaMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a EstatusIncidenciaEntity by calling a Stored Procedure
        /// </summary>
        public Objects.EstatusIncidenciaObject GetOne(System.Int32 Clave) {
            return Instance().GetOne( Clave);
        }

        // GetBy Objects and Params
            

        

       

            

        
        /// <summary>
        /// Delete EstatusIncidencia 
        /// </summary>
        public void Delete(System.Int32 Clave){
            Instance().Delete(Clave);
        }

        /// <summary>
        /// Delete EstatusIncidenciaObject 
        /// </summary>
        public void Delete(Objects.EstatusIncidenciaObject entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save EstatusIncidenciaObject  
        /// </summary>
        public void Save(Objects.EstatusIncidenciaObject entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert EstatusIncidenciaObject 
        /// </summary>
        public void Insert(Objects.EstatusIncidenciaObject entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll EstatusIncidenciaObject 
        /// </summary>
        public Objects.EstatusIncidenciaObjectList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save EstatusIncidencia 
        /// </summary>
        public void Save(System.Int32 Clave, System.String Descripcion){
            Objects.EstatusIncidenciaObject entity = Instance().GetOne(Clave);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "Clave", Clave));

            entity.Descripcion = Descripcion;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert EstatusIncidenciaObject
        /// </summary>
        public void Insert(System.String Descripcion){
            Objects.EstatusIncidenciaObject entity = new Objects.EstatusIncidenciaObject();

            entity.Descripcion = Descripcion;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class EstatusIncidenciaLoader<T> : BaseLoader< T, EstatusIncidenciaObject, ObjectList<T>>, IGenericGateway where T : EstatusIncidenciaObject, new()
    {

        #region "Singleton"

        static EstatusIncidenciaLoader<T> _instance;

        private EstatusIncidenciaLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static EstatusIncidenciaLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new EstatusIncidenciaLoader<T>();
                else {
                    EstatusIncidenciaLoader<T> inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.EstatusIncidenciaLoaderSingleton"] as EstatusIncidenciaLoader<T>;
                    if (inst == null) {
                        inst = new EstatusIncidenciaLoader<T>();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.EstatusIncidenciaLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(EstatusIncidenciaObject);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "EstatusIncidencia"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, EstatusIncidenciaObject entity)
        {
            
            IMappeableEstatusIncidenciaObject EstatusIncidencia = (IMappeableEstatusIncidenciaObject)entity;
            EstatusIncidencia.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? "" : reader.GetString(1));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        



        /// <summary>
        /// Get a EstatusIncidencia by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a EstatusIncidenciaList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 Clave)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "EstatusIncidencia_GetOne", Clave);
        }


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





