
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 28/07/2009 - 08:51 p.m.
// This is a partial class file. The other one is CorporacionObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CorporacionObject : BaseObject, IMappeableCorporacionObject, IUniqueIdentifiable, IEquatable<CorporacionObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public CorporacionObject(): base()
        {

			_Clave =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public CorporacionObject(
			System.Int32 Clave): base()
        {

			_Clave = Clave;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public CorporacionObject(
			System.Int32 Clave,
			System.String Descripcion,
			System.Nullable<System.Int32> ClaveSistema,
			System.Boolean UnidadesVirtuales,
			System.Boolean Activo): base()
        {

			_Clave = Clave;
			_Descripcion = Descripcion;
			_ClaveSistema = ClaveSistema;
			_UnidadesVirtuales = UnidadesVirtuales;
			_Activo = Activo;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Clave;
/// <summary>
/// 
/// </summary>
protected System.String _Descripcion;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveSistema;
/// <summary>
/// 
/// </summary>
protected System.Boolean _UnidadesVirtuales;
/// <summary>
/// 
/// </summary>
protected System.Boolean _Activo;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Clave
        {
            get
            {
                return _Clave;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            
            set
            {
                base.PropertyModified();
                _Descripcion = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveSistema
        {
            get
            {
                return _ClaveSistema;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveSistema = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean UnidadesVirtuales
        {
            get
            {
                return _UnidadesVirtuales;
            }
            
            set
            {
                base.PropertyModified();
                _UnidadesVirtuales = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            
            set
            {
                base.PropertyModified();
                _Activo = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            CorporacionObject newObject;
            CorporacionObject newOriginalValue;

            newObject = (CorporacionObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (CorporacionObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new CorporacionObject OriginalValue()
        {
            return (CorporacionObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCorporacionObject.HydrateFields(
			System.Int32 Clave,
			System.String Descripcion,
			System.Nullable<System.Int32> ClaveSistema,
			System.Boolean UnidadesVirtuales,
			System.Boolean Activo)
        {
        _Clave = Clave;
_Descripcion = Descripcion;
_ClaveSistema = ClaveSistema;
_UnidadesVirtuales = UnidadesVirtuales;
_Activo = Activo;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCorporacionObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[5];
            _myArray[0] = _Clave;
_myArray[1] = _Descripcion;
if (_ClaveSistema.HasValue) _myArray[2] = _ClaveSistema.Value;
_myArray[3] = _UnidadesVirtuales;
_myArray[4] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCorporacionObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[5];
            _myArray[0] = _Clave;
_myArray[1] = _Descripcion;
if (_ClaveSistema.HasValue) _myArray[2] = _ClaveSistema.Value;
_myArray[3] = _UnidadesVirtuales;
_myArray[4] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableCorporacionObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Clave;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableCorporacionObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Clave = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            CorporacionObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Clave};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(CorporacionObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableCorporacionObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Clave, 
			System.String Descripcion, 
			System.Nullable<System.Int32> ClaveSistema, 
			System.Boolean UnidadesVirtuales, 
			System.Boolean Activo);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class CorporacionObjectList : ObjectList<CorporacionObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class CorporacionObjectListView
        : ObjectListView<Objects.CorporacionObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public CorporacionObjectListView(Objects.CorporacionObjectList list): base(list)
        {
        }
    }
}


