
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 28/07/2009 - 08:51 p.m.
// This is a partial class file. The other one is DetalleDespachoIncidenciaEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class DetalleDespachoIncidencia : Objects.DetalleDespachoIncidenciaObject, IMappeableDetalleDespachoIncidencia, IEquatable<DetalleDespachoIncidencia>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidencia()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidencia(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidencia(
			System.Int32 Clave,
			System.Int32 ClaveDespacho,
			System.String Descripcion,
			System.Int32 ClaveUsuario,
			System.DateTime HoraRegistro)
            : base()
        {

			_Clave = Clave;
			_ClaveDespacho = ClaveDespacho;
			_Descripcion = Descripcion;
			_ClaveUsuario = ClaveUsuario;
			_HoraRegistro = HoraRegistro;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new DetalleDespachoIncidencia OriginalValue()
        {
            return (DetalleDespachoIncidencia)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            DetalleDespachoIncidencia newObject;            
            

            newObject = (DetalleDespachoIncidencia)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            DetalleDespachoIncidencia newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (DetalleDespachoIncidencia)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableDetalleDespachoIncidencia.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableDetalleDespachoIncidencia.SetFKValuesForChilds(DetalleDespachoIncidencia entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(DetalleDespachoIncidencia other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableDetalleDespachoIncidencia
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(DetalleDespachoIncidencia entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class DetalleDespachoIncidenciaList : ObjectList<DetalleDespachoIncidencia>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class DetalleDespachoIncidenciaListView
        : ObjectListView<Entities.DetalleDespachoIncidencia>
    {
        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaListView(Entities.DetalleDespachoIncidenciaList list): base(list)
        {
        }
    }
}


