
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 15/08/2009 - 05:12 p.m.
// This is a partial class file. The other one is BitacoraEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Bitacora : Objects.BitacoraObject, IMappeableBitacora, IEquatable<Bitacora>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Bitacora()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Bitacora(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Bitacora(
			System.Int32 Clave,
			System.String NombreCatalogo,
			System.String Descripcion,
			System.String NombrePropio,
			System.String Operacion,
			System.Nullable<System.DateTime> FechaOperacion,
			System.String ValorAnterior,
			System.String ValorActual)
            : base()
        {

			_Clave = Clave;
			_NombreCatalogo = NombreCatalogo;
			_Descripcion = Descripcion;
			_NombrePropio = NombrePropio;
			_Operacion = Operacion;
			_FechaOperacion = FechaOperacion;
			_ValorAnterior = ValorAnterior;
			_ValorActual = ValorActual;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Bitacora OriginalValue()
        {
            return (Bitacora)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Bitacora newObject;            
            

            newObject = (Bitacora)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Bitacora newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Bitacora)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableBitacora.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableBitacora.SetFKValuesForChilds(Bitacora entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Bitacora other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableBitacora
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Bitacora entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class BitacoraList : ObjectList<Bitacora>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class BitacoraListView
        : ObjectListView<Entities.Bitacora>
    {
        /// <summary>
        /// 
        /// </summary>
        public BitacoraListView(Entities.BitacoraList list): base(list)
        {
        }
    }
}


