
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 05/08/2009 - 03:37 p.m.
// This is a partial class file. The other one is CodigoPostalEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class CodigoPostal : Objects.CodigoPostalObject, IMappeableCodigoPostal, IEquatable<CodigoPostal>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public CodigoPostal()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public CodigoPostal(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public CodigoPostal(
			System.Int32 Clave,
			System.String Valor)
            : base()
        {

			_Clave = Clave;
			_Valor = Valor;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new CodigoPostal OriginalValue()
        {
            return (CodigoPostal)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            CodigoPostal newObject;            
            

            newObject = (CodigoPostal)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            CodigoPostal newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (CodigoPostal)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableCodigoPostal.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableCodigoPostal.SetFKValuesForChilds(CodigoPostal entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(CodigoPostal other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableCodigoPostal
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(CodigoPostal entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class CodigoPostalList : ObjectList<CodigoPostal>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class CodigoPostalListView
        : ObjectListView<Entities.CodigoPostal>
    {
        /// <summary>
        /// 
        /// </summary>
        public CodigoPostalListView(Entities.CodigoPostalList list): base(list)
        {
        }
    }
}


