
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 05/08/2009 - 10:00 p.m.
// This is a partial class file. The other one is ColoniaEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Colonia : Objects.ColoniaObject, IMappeableColonia, IEquatable<Colonia>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Colonia()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Colonia(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Colonia(
			System.Int32 Clave,
			System.Int32 ClaveLocalidad,
			System.String Nombre,
			System.Nullable<System.Int32> ClaveCodigoPostal)
            : base()
        {

			_Clave = Clave;
			_ClaveLocalidad = ClaveLocalidad;
			_Nombre = Nombre;
			_ClaveCodigoPostal = ClaveCodigoPostal;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Colonia OriginalValue()
        {
            return (Colonia)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Colonia newObject;            
            

            newObject = (Colonia)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Colonia newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Colonia)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableColonia.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableColonia.SetFKValuesForChilds(Colonia entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Colonia other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableColonia
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Colonia entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class ColoniaList : ObjectList<Colonia>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class ColoniaListView
        : ObjectListView<Entities.Colonia>
    {
        /// <summary>
        /// 
        /// </summary>
        public ColoniaListView(Entities.ColoniaList list): base(list)
        {
        }
    }
}


