
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 29/07/2009 - 02:18 p.m.
// This is a partial class file. The other one is SubmoduloEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Submodulo : Objects.SubmoduloObject, IMappeableSubmodulo, IEquatable<Submodulo>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Submodulo()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Submodulo(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Submodulo(
			System.Int32 Clave,
			System.Int32 ClaveSistema,
			System.String Descripcion)
            : base()
        {

			_Clave = Clave;
			_ClaveSistema = ClaveSistema;
			_Descripcion = Descripcion;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Submodulo OriginalValue()
        {
            return (Submodulo)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Submodulo newObject;            
            

            newObject = (Submodulo)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Submodulo newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Submodulo)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableSubmodulo.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableSubmodulo.SetFKValuesForChilds(Submodulo entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Submodulo other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableSubmodulo
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Submodulo entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class SubmoduloList : ObjectList<Submodulo>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class SubmoduloListView
        : ObjectListView<Entities.Submodulo>
    {
        /// <summary>
        /// 
        /// </summary>
        public SubmoduloListView(Entities.SubmoduloList list): base(list)
        {
        }
    }
}


