

//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 04/08/2009 - 01:50 p.m.
// This is a partial class file. The other one is IncidenciaGateway.Auto.cs
// You can edit this file as your wish.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Core;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using System.Data.Common;
using System.Reflection;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Gateways
{

    /// <summary>
    /// Gateway between IncidenciaObject class and Incidencia table.
    /// This class provide CRUD methods for Incidencia table.
    /// </summary>
    public partial class IncidenciaGateway
    {
        /// <summary>
        /// Enables GetObjectBySQLText and GetObjectListBySQLText methods.
        /// </summary>
        protected override bool SQLQueriesEnabled()
        {
            return true;
        }


        // /// <summary>
        // /// Checks for security ritghs
        // /// </summary>
        //protected override bool CheckForSecurityRights(SecurityRights action, IncidenciaObjectList ObjectListOrEntityList)
        //{
        //    switch (action)
        //    {
        //        case SecurityRights.Read:
        //            return true;
        //        case SecurityRights.Insert:
        //            return true;
        //        case SecurityRights.Update:
        //            return true;
        //        case SecurityRights.Delete:
        //            return true;
        //    }
        //    return false;
        //}

    }

}



