
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 15/08/2009 - 05:12 p.m.
// This is a partial class file. The other one is BitacoraGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Gateways
{

    public partial class BitacoraGateway : BaseGateway<BitacoraObject, BitacoraObjectList>, IGenericGateway
    {

        #region "Singleton"

        static BitacoraGateway _instance;

        private BitacoraGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static BitacoraGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new BitacoraGateway();
                else {
                    BitacoraGateway inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.BitacoraGatewaySingleton"] as BitacoraGateway;
                    if (inst == null) {
                        inst = new BitacoraGateway();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.BitacoraGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Bitacora"; }
        }

        protected override string RuleName
        {
            get {return typeof(BitacoraGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, BitacoraObject entity)
        {
            
            IMappeableBitacoraObject Bitacora = (IMappeableBitacoraObject)entity;
            Bitacora.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? "" : reader.GetString(1),
(reader.IsDBNull(2)) ? "" : reader.GetString(2),
(reader.IsDBNull(3)) ? "" : reader.GetString(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
(reader.IsDBNull(5)) ? new System.Nullable<System.DateTime>() : reader.GetDateTime(5),
(reader.IsDBNull(6)) ? "" : reader.GetString(6),
(reader.IsDBNull(7)) ? "" : reader.GetString(7));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(BitacoraObject entity)
        {

            IMappeableBitacoraObject Bitacora = (IMappeableBitacoraObject)entity;
            return Bitacora.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(BitacoraObject entity)
        {

            IMappeableBitacoraObject Bitacora = (IMappeableBitacoraObject)entity;
            return Bitacora.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(BitacoraObject entity)
        {

            IMappeableBitacoraObject Bitacora = (IMappeableBitacoraObject)entity;
            return Bitacora.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(BitacoraObject row, object[] parameters)
        {
            ((IMappeableBitacoraObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        /// <summary>
        /// Get a BitacoraObject by execute a SQL Query Text
        /// </summary>
        public BitacoraObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a BitacoraObjectList by execute a SQL Query Text
        /// </summary>
        public BitacoraObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a BitacoraObject by calling a Stored Procedure
        /// </summary>
        public BitacoraObject GetOne(System.Int32 Clave)
        {
            return base.GetOne(new BitacoraObject(Clave));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete Bitacora
        /// </summary>
        public void Delete(System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Bitacora_Delete", Clave);
        }

        /// <summary>
        /// Delete Bitacora
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Bitacora_Delete", Clave);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








