
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 04/08/2009 - 01:50 p.m.
// This is a partial class file. The other one is VehiculoGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Gateways
{

    public partial class VehiculoGateway : BaseGateway<VehiculoObject, VehiculoObjectList>, IGenericGateway
    {

        #region "Singleton"

        static VehiculoGateway _instance;

        private VehiculoGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static VehiculoGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new VehiculoGateway();
                else {
                    VehiculoGateway inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.VehiculoGatewaySingleton"] as VehiculoGateway;
                    if (inst == null) {
                        inst = new VehiculoGateway();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.VehiculoGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "Vehiculo"; }
        }

        protected override string RuleName
        {
            get {return typeof(VehiculoGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, VehiculoObject entity)
        {
            
            IMappeableVehiculoObject Vehiculo = (IMappeableVehiculoObject)entity;
            Vehiculo.HydrateFields(
            reader.GetInt32(0),
(reader.IsDBNull(1)) ? "" : reader.GetString(1),
(reader.IsDBNull(2)) ? "" : reader.GetString(2),
(reader.IsDBNull(3)) ? "" : reader.GetString(3),
(reader.IsDBNull(4)) ? "" : reader.GetString(4),
(reader.IsDBNull(5)) ? "" : reader.GetString(5),
(reader.IsDBNull(6)) ? "" : reader.GetString(6),
(reader.IsDBNull(7)) ? "" : reader.GetString(7));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(VehiculoObject entity)
        {

            IMappeableVehiculoObject Vehiculo = (IMappeableVehiculoObject)entity;
            return Vehiculo.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(VehiculoObject entity)
        {

            IMappeableVehiculoObject Vehiculo = (IMappeableVehiculoObject)entity;
            return Vehiculo.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(VehiculoObject entity)
        {

            IMappeableVehiculoObject Vehiculo = (IMappeableVehiculoObject)entity;
            return Vehiculo.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(VehiculoObject row, object[] parameters)
        {
            ((IMappeableVehiculoObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        /// <summary>
        /// Get a VehiculoObject by execute a SQL Query Text
        /// </summary>
        public VehiculoObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a VehiculoObjectList by execute a SQL Query Text
        /// </summary>
        public VehiculoObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a VehiculoObject by calling a Stored Procedure
        /// </summary>
        public VehiculoObject GetOne(System.Int32 Clave)
        {
            return base.GetOne(new VehiculoObject(Clave));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete Vehiculo
        /// </summary>
        public void Delete(System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Vehiculo_Delete", Clave);
        }

        /// <summary>
        /// Delete Vehiculo
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Vehiculo_Delete", Clave);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








