
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 28/07/2009 - 08:51 p.m.
// This is a partial class file. The other one is DetalleDespachoIncidenciaObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class DetalleDespachoIncidenciaObject : BaseObject, IMappeableDetalleDespachoIncidenciaObject, IUniqueIdentifiable, IEquatable<DetalleDespachoIncidenciaObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaObject(): base()
        {

			_Clave =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaObject(
			System.Int32 Clave): base()
        {

			_Clave = Clave;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaObject(
			System.Int32 Clave,
			System.Int32 ClaveDespacho,
			System.String Descripcion,
			System.Int32 ClaveUsuario,
			System.DateTime HoraRegistro): base()
        {

			_Clave = Clave;
			_ClaveDespacho = ClaveDespacho;
			_Descripcion = Descripcion;
			_ClaveUsuario = ClaveUsuario;
			_HoraRegistro = HoraRegistro;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Clave;
/// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveDespacho;
/// <summary>
/// 
/// </summary>
protected System.String _Descripcion;
/// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveUsuario;
/// <summary>
/// 
/// </summary>
protected System.DateTime _HoraRegistro;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Clave
        {
            get
            {
                return _Clave;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveDespacho
        {
            get
            {
                return _ClaveDespacho;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveDespacho = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            
            set
            {
                base.PropertyModified();
                _Descripcion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveUsuario
        {
            get
            {
                return _ClaveUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.DateTime HoraRegistro
        {
            get
            {
                return _HoraRegistro;
            }
            
            set
            {
                base.PropertyModified();
                _HoraRegistro = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            DetalleDespachoIncidenciaObject newObject;
            DetalleDespachoIncidenciaObject newOriginalValue;

            newObject = (DetalleDespachoIncidenciaObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (DetalleDespachoIncidenciaObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new DetalleDespachoIncidenciaObject OriginalValue()
        {
            return (DetalleDespachoIncidenciaObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableDetalleDespachoIncidenciaObject.HydrateFields(
			System.Int32 Clave,
			System.Int32 ClaveDespacho,
			System.String Descripcion,
			System.Int32 ClaveUsuario,
			System.DateTime HoraRegistro)
        {
        _Clave = Clave;
_ClaveDespacho = ClaveDespacho;
_Descripcion = Descripcion;
_ClaveUsuario = ClaveUsuario;
_HoraRegistro = HoraRegistro;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableDetalleDespachoIncidenciaObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[5];
            _myArray[0] = _Clave;
_myArray[1] = _ClaveDespacho;
_myArray[2] = _Descripcion;
_myArray[3] = _ClaveUsuario;
_myArray[4] = _HoraRegistro;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableDetalleDespachoIncidenciaObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[5];
            _myArray[0] = _Clave;
_myArray[1] = _ClaveDespacho;
_myArray[2] = _Descripcion;
_myArray[3] = _ClaveUsuario;
_myArray[4] = _HoraRegistro;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableDetalleDespachoIncidenciaObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Clave;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableDetalleDespachoIncidenciaObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Clave = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            DetalleDespachoIncidenciaObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Clave};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(DetalleDespachoIncidenciaObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableDetalleDespachoIncidenciaObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Clave, 
			System.Int32 ClaveDespacho, 
			System.String Descripcion, 
			System.Int32 ClaveUsuario, 
			System.DateTime HoraRegistro);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class DetalleDespachoIncidenciaObjectList : ObjectList<DetalleDespachoIncidenciaObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class DetalleDespachoIncidenciaObjectListView
        : ObjectListView<Objects.DetalleDespachoIncidenciaObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaObjectListView(Objects.DetalleDespachoIncidenciaObjectList list): base(list)
        {
        }
    }
}


