
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 28/07/2009 - 08:51 p.m.
// This is a partial class file. The other one is DetalleDespachoIncidenciaMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities;
using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class DetalleDespachoIncidenciaMapper : BaseGateway<DetalleDespachoIncidencia, DetalleDespachoIncidenciaList>, IGenericGateway
    {


        #region "Singleton"

        static DetalleDespachoIncidenciaMapper _instance;

        private DetalleDespachoIncidenciaMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static DetalleDespachoIncidenciaMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new DetalleDespachoIncidenciaMapper();
                else {
                    DetalleDespachoIncidenciaMapper inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.DetalleDespachoIncidenciaMapperSingleton"] as DetalleDespachoIncidenciaMapper;
                    if (inst == null) {
                        inst = new DetalleDespachoIncidenciaMapper();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.DetalleDespachoIncidenciaMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(DetalleDespachoIncidencia);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "DetalleDespachoIncidencia"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(DetalleDespachoIncidenciaMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, DetalleDespachoIncidencia entity)
        {
            
            IMappeableDetalleDespachoIncidenciaObject DetalleDespachoIncidencia = (IMappeableDetalleDespachoIncidenciaObject)entity;
            DetalleDespachoIncidencia.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetString(2),
reader.GetInt32(3),
reader.GetDateTime(4));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(DetalleDespachoIncidencia entity)
        {

            IMappeableDetalleDespachoIncidenciaObject DetalleDespachoIncidencia = (IMappeableDetalleDespachoIncidenciaObject)entity;
            return DetalleDespachoIncidencia.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(DetalleDespachoIncidencia entity)
        {

            IMappeableDetalleDespachoIncidenciaObject DetalleDespachoIncidencia = (IMappeableDetalleDespachoIncidenciaObject)entity;
            return DetalleDespachoIncidencia.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(DetalleDespachoIncidencia entity)
        {

            IMappeableDetalleDespachoIncidenciaObject DetalleDespachoIncidencia = (IMappeableDetalleDespachoIncidenciaObject)entity;
            return DetalleDespachoIncidencia.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(DetalleDespachoIncidencia entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableDetalleDespachoIncidenciaObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(DetalleDespachoIncidencia entity)
        {
            
            ((IMappeableDetalleDespachoIncidencia)entity).CompleteEntity();
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a DetalleDespachoIncidencia by execute a SQL Query Text
        /// </summary>
        public DetalleDespachoIncidencia GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a DetalleDespachoIncidenciaList by execute a SQL Query Text
        /// </summary>
        public DetalleDespachoIncidenciaList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidencia GetOne(System.Int32 Clave)
        {
            return base.GetOne(new DetalleDespachoIncidencia(Clave));
        }


        // GetOne By Objects and Params
            


        

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByDespachoIncidencia(DbTransaction transaction, System.Int32 ClaveDespacho)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", ClaveDespacho);
        }

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByDespachoIncidencia(DbTransaction transaction, IUniqueIdentifiable DespachoIncidencia)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", DespachoIncidencia.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByUsuario(DbTransaction transaction, System.Int32 ClaveUsuario)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", ClaveUsuario);
        }

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByUsuario(DbTransaction transaction, IUniqueIdentifiable Usuario)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", Usuario.Identifier());
        }

    


        

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByDespachoIncidencia(System.Int32 ClaveDespacho)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", ClaveDespacho);
        }

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByDespachoIncidencia(IUniqueIdentifiable DespachoIncidencia)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", DespachoIncidencia.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByUsuario(System.Int32 ClaveUsuario)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", ClaveUsuario);
        }

        /// <summary>
        /// 
        /// </summary>
        public DetalleDespachoIncidenciaList GetByUsuario(IUniqueIdentifiable Usuario)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", Usuario.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_Delete", Clave);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 Clave)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_Delete", Clave);
        }


        // Delete By Objects and Params
            



        

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByDespachoIncidencia(System.Int32 ClaveDespacho)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByDespachoIncidencia", ClaveDespacho);
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByDespachoIncidencia(DbTransaction transaction, System.Int32 ClaveDespacho)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByDespachoIncidencia", ClaveDespacho);
        }


        /// <summary>
        /// 
        /// </summary>
        public void DeleteByDespachoIncidencia(IUniqueIdentifiable DespachoIncidencia)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByDespachoIncidencia", DespachoIncidencia.Identifier());
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByDespachoIncidencia(DbTransaction transaction, IUniqueIdentifiable DespachoIncidencia)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByDespachoIncidencia", DespachoIncidencia.Identifier());
        }


    

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUsuario(System.Int32 ClaveUsuario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByUsuario", ClaveUsuario);
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUsuario(DbTransaction transaction, System.Int32 ClaveUsuario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByUsuario", ClaveUsuario);
        }


        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUsuario(IUniqueIdentifiable Usuario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByUsuario", Usuario.Identifier());
        }

        /// <summary>
        /// 
        /// </summary>
        public void DeleteByUsuario(DbTransaction transaction, IUniqueIdentifiable Usuario)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_DeleteByUsuario", Usuario.Identifier());
        }


    


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class DetalleDespachoIncidenciaMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.DetalleDespachoIncidenciaMapper Instance()
        {
            return BSD.C4.Tlaxcala.Sai.Dal.Rules.Mappers.DetalleDespachoIncidenciaMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a DetalleDespachoIncidenciaEntity by calling a Stored Procedure
        /// </summary>
        public Entities.DetalleDespachoIncidencia GetOne(System.Int32 Clave) {
            return Instance().GetOne( Clave);
        }

        // GetBy Objects and Params
            

        

        /// <summary>
        /// Get a DetalleDespachoIncidenciaList by calling a Stored Procedure
        /// </summary>
        public Entities.DetalleDespachoIncidenciaList GetByDespachoIncidencia(System.Int32 ClaveDespacho)
        {
            return Instance().GetByDespachoIncidencia(ClaveDespacho);
        }

        /// <summary>
        /// Get a DetalleDespachoIncidenciaList by calling a Stored Procedure
        /// </summary>
        public Entities.DetalleDespachoIncidenciaList GetByDespachoIncidencia(IUniqueIdentifiable DespachoIncidencia)
        {
            return Instance().GetByDespachoIncidencia(DespachoIncidencia);
        }

    

        /// <summary>
        /// Get a DetalleDespachoIncidenciaList by calling a Stored Procedure
        /// </summary>
        public Entities.DetalleDespachoIncidenciaList GetByUsuario(System.Int32 ClaveUsuario)
        {
            return Instance().GetByUsuario(ClaveUsuario);
        }

        /// <summary>
        /// Get a DetalleDespachoIncidenciaList by calling a Stored Procedure
        /// </summary>
        public Entities.DetalleDespachoIncidenciaList GetByUsuario(IUniqueIdentifiable Usuario)
        {
            return Instance().GetByUsuario(Usuario);
        }

    

       

        /// <summary>
        /// Delete children for DetalleDespachoIncidencia
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, DetalleDespachoIncidencia entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        

        /// <summary>
        /// Delete DetalleDespachoIncidencia by DespachoIncidencia
        /// </summary>
        public void DeleteByDespachoIncidencia(System.Int32 ClaveDespacho)
        {
            Instance().DeleteByDespachoIncidencia(ClaveDespacho);
        }

        /// <summary>
        /// Delete DetalleDespachoIncidencia by DespachoIncidencia
        /// </summary>
        public void DeleteByDespachoIncidencia(IUniqueIdentifiable DespachoIncidencia)
        {
            Instance().DeleteByDespachoIncidencia(DespachoIncidencia);
        }

    

        /// <summary>
        /// Delete DetalleDespachoIncidencia by Usuario
        /// </summary>
        public void DeleteByUsuario(System.Int32 ClaveUsuario)
        {
            Instance().DeleteByUsuario(ClaveUsuario);
        }

        /// <summary>
        /// Delete DetalleDespachoIncidencia by Usuario
        /// </summary>
        public void DeleteByUsuario(IUniqueIdentifiable Usuario)
        {
            Instance().DeleteByUsuario(Usuario);
        }

    
        /// <summary>
        /// Delete DetalleDespachoIncidencia 
        /// </summary>
        public void Delete(System.Int32 Clave){
            Instance().Delete(Clave);
        }

        /// <summary>
        /// Delete DetalleDespachoIncidencia 
        /// </summary>
        public void Delete(Entities.DetalleDespachoIncidencia entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save DetalleDespachoIncidencia  
        /// </summary>
        public void Save(Entities.DetalleDespachoIncidencia entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert DetalleDespachoIncidencia 
        /// </summary>
        public void Insert(Entities.DetalleDespachoIncidencia entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll DetalleDespachoIncidencia 
        /// </summary>
        public Entities.DetalleDespachoIncidenciaList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save DetalleDespachoIncidencia 
        /// </summary>
        public void Save(System.Int32 Clave, System.Int32 ClaveDespacho, System.String Descripcion, System.Int32 ClaveUsuario, System.DateTime HoraRegistro){
            Entities.DetalleDespachoIncidencia entity = Instance().GetOne(Clave);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "Clave", Clave));

            entity.ClaveDespacho = ClaveDespacho;
            entity.Descripcion = Descripcion;
            entity.ClaveUsuario = ClaveUsuario;
            entity.HoraRegistro = HoraRegistro;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert DetalleDespachoIncidencia
        /// </summary>
        public void Insert(System.Int32 ClaveDespacho, System.String Descripcion, System.Int32 ClaveUsuario, System.DateTime HoraRegistro){
            Entities.DetalleDespachoIncidencia entity = new Entities.DetalleDespachoIncidencia();

            entity.ClaveDespacho = ClaveDespacho;
            entity.Descripcion = Descripcion;
            entity.ClaveUsuario = ClaveUsuario;
            entity.HoraRegistro = HoraRegistro;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class DetalleDespachoIncidenciaLoader<T> : BaseLoader< T, DetalleDespachoIncidencia, ObjectList<T>>, IGenericGateway where T : DetalleDespachoIncidencia, new()
    {

        #region "Singleton"

        static DetalleDespachoIncidenciaLoader<T> _instance;

        private DetalleDespachoIncidenciaLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static DetalleDespachoIncidenciaLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new DetalleDespachoIncidenciaLoader<T>();
                else {
                    DetalleDespachoIncidenciaLoader<T> inst = HttpContext.Current.Items["BSD.C4.Tlaxcala.Sai.Dal.Rules.DetalleDespachoIncidenciaLoaderSingleton"] as DetalleDespachoIncidenciaLoader<T>;
                    if (inst == null) {
                        inst = new DetalleDespachoIncidenciaLoader<T>();
                        HttpContext.Current.Items.Add("BSD.C4.Tlaxcala.Sai.Dal.Rules.DetalleDespachoIncidenciaLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"Clave"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(DetalleDespachoIncidencia);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "DetalleDespachoIncidencia"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, DetalleDespachoIncidencia entity)
        {
            
            IMappeableDetalleDespachoIncidenciaObject DetalleDespachoIncidencia = (IMappeableDetalleDespachoIncidenciaObject)entity;
            DetalleDespachoIncidencia.HydrateFields(
            reader.GetInt32(0),
reader.GetInt32(1),
reader.GetString(2),
reader.GetInt32(3),
reader.GetDateTime(4));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "up_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            
            ((IMappeableDetalleDespachoIncidencia)entity).CompleteEntity();
        }


        



        /// <summary>
        /// Get a DetalleDespachoIncidencia by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a DetalleDespachoIncidenciaList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 Clave)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetOne", Clave);
        }


        // GetOne By Objects and Params
            


        

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByDespachoIncidencia(DbTransaction transaction, System.Int32 ClaveDespacho)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", ClaveDespacho);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByDespachoIncidencia(DbTransaction transaction, IUniqueIdentifiable DespachoIncidencia)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", DespachoIncidencia.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUsuario(DbTransaction transaction, System.Int32 ClaveUsuario)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", ClaveUsuario);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUsuario(DbTransaction transaction, IUniqueIdentifiable Usuario)
        {
            return base.GetObjectListByAnyStoredProcedure(transaction, StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", Usuario.Identifier());
        }

    


        

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByDespachoIncidencia(System.Int32 ClaveDespacho)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", ClaveDespacho);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByDespachoIncidencia(IUniqueIdentifiable DespachoIncidencia)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByDespachoIncidencia", DespachoIncidencia.Identifier());
        }

    

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUsuario(System.Int32 ClaveUsuario)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", ClaveUsuario);
        }

        /// <summary>
        /// 
        /// </summary>
        public ObjectList<T> GetByUsuario(IUniqueIdentifiable Usuario)
        {
            return base.GetObjectListByAnyStoredProcedure(StoredProceduresPrefix() + "DetalleDespachoIncidencia_GetByUsuario", Usuario.Identifier());
        }

    

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





