
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 8/31/2009 - 11:48 PM
// This is a partial class file. The other one is IncidenciaObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class IncidenciaObject : BaseObject, IMappeableIncidenciaObject, IUniqueIdentifiable, IEquatable<IncidenciaObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public IncidenciaObject(): base()
        {

			_Folio =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public IncidenciaObject(
			System.Int32 Folio): base()
        {

			_Folio = Folio;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public IncidenciaObject(
			System.Int32 Folio,
			System.Nullable<System.Int32> FolioPadre,
			System.String Descripcion,
			System.String Direccion,
			System.String Referencias,
			System.DateTime HoraRecepcion,
			System.Nullable<System.Int32> ClaveEstado,
			System.Nullable<System.Int32> ClaveMunicipio,
			System.Nullable<System.Int32> ClaveLocalidad,
			System.Nullable<System.Int32> ClaveColonia,
			System.Nullable<System.Int32> ClaveCodigoPostal,
			System.String Telefono,
			System.Nullable<System.Int32> ClaveDenunciante,
			System.Int32 ClaveEstatus,
			System.Int32 ClaveUsuario,
			System.Boolean Activo,
			System.Nullable<System.Int32> ClaveTipo,
			System.Nullable<System.Int32> Prioridad,
			System.Nullable<System.DateTime> FechaDocumento,
			System.String NumeroOficio,
			System.Nullable<System.DateTime> FechaSuceso,
			System.String AliasDelincuente,
			System.Byte[] Imagen,
			System.Nullable<System.Int32> ClaveCoordenada): base()
        {

			_Folio = Folio;
			_FolioPadre = FolioPadre;
			_Descripcion = Descripcion;
			_Direccion = Direccion;
			_Referencias = Referencias;
			_HoraRecepcion = HoraRecepcion;
			_ClaveEstado = ClaveEstado;
			_ClaveMunicipio = ClaveMunicipio;
			_ClaveLocalidad = ClaveLocalidad;
			_ClaveColonia = ClaveColonia;
			_ClaveCodigoPostal = ClaveCodigoPostal;
			_Telefono = Telefono;
			_ClaveDenunciante = ClaveDenunciante;
			_ClaveEstatus = ClaveEstatus;
			_ClaveUsuario = ClaveUsuario;
			_Activo = Activo;
			_ClaveTipo = ClaveTipo;
			_Prioridad = Prioridad;
			_FechaDocumento = FechaDocumento;
			_NumeroOficio = NumeroOficio;
			_FechaSuceso = FechaSuceso;
			_AliasDelincuente = AliasDelincuente;
			_Imagen = Imagen;
			_ClaveCoordenada = ClaveCoordenada;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Folio;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _FolioPadre;
/// <summary>
/// 
/// </summary>
protected System.String _Descripcion;
/// <summary>
/// 
/// </summary>
protected System.String _Direccion;
/// <summary>
/// 
/// </summary>
protected System.String _Referencias;
/// <summary>
/// 
/// </summary>
protected System.DateTime _HoraRecepcion;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveEstado;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveMunicipio;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveLocalidad;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveColonia;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveCodigoPostal;
/// <summary>
/// 
/// </summary>
protected System.String _Telefono;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveDenunciante;
/// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveEstatus;
/// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveUsuario;
/// <summary>
/// 
/// </summary>
protected System.Boolean _Activo;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveTipo;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _Prioridad;
/// <summary>
///
/// </summary>
protected System.Nullable<System.DateTime> _FechaDocumento;
/// <summary>
/// 
/// </summary>
protected System.String _NumeroOficio;
/// <summary>
///
/// </summary>
protected System.Nullable<System.DateTime> _FechaSuceso;
/// <summary>
/// 
/// </summary>
protected System.String _AliasDelincuente;
/// <summary>
/// 
/// </summary>
protected System.Byte[] _Imagen;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveCoordenada;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Folio
        {
            get
            {
                return _Folio;
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> FolioPadre
        {
            get
            {
                return _FolioPadre;
            }
            
            set
            {
                base.PropertyModified();
                _FolioPadre = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            
            set
            {
                base.PropertyModified();
                _Descripcion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            
            set
            {
                base.PropertyModified();
                _Direccion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Referencias
        {
            get
            {
                return _Referencias;
            }
            
            set
            {
                base.PropertyModified();
                _Referencias = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.DateTime HoraRecepcion
        {
            get
            {
                return _HoraRecepcion;
            }
            
            set
            {
                base.PropertyModified();
                _HoraRecepcion = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveEstado
        {
            get
            {
                return _ClaveEstado;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveEstado = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveMunicipio
        {
            get
            {
                return _ClaveMunicipio;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveMunicipio = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveLocalidad
        {
            get
            {
                return _ClaveLocalidad;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveLocalidad = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveColonia
        {
            get
            {
                return _ClaveColonia;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveColonia = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveCodigoPostal
        {
            get
            {
                return _ClaveCodigoPostal;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveCodigoPostal = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            
            set
            {
                base.PropertyModified();
                _Telefono = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveDenunciante
        {
            get
            {
                return _ClaveDenunciante;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveDenunciante = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveEstatus
        {
            get
            {
                return _ClaveEstatus;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveEstatus = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveUsuario
        {
            get
            {
                return _ClaveUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            
            set
            {
                base.PropertyModified();
                _Activo = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveTipo
        {
            get
            {
                return _ClaveTipo;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveTipo = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> Prioridad
        {
            get
            {
                return _Prioridad;
            }
            
            set
            {
                base.PropertyModified();
                _Prioridad = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaDocumento
        {
            get
            {
                return _FechaDocumento;
            }
            
            set
            {
                base.PropertyModified();
                _FechaDocumento = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String NumeroOficio
        {
            get
            {
                return _NumeroOficio;
            }
            
            set
            {
                base.PropertyModified();
                _NumeroOficio = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaSuceso
        {
            get
            {
                return _FechaSuceso;
            }
            
            set
            {
                base.PropertyModified();
                _FechaSuceso = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String AliasDelincuente
        {
            get
            {
                return _AliasDelincuente;
            }
            
            set
            {
                base.PropertyModified();
                _AliasDelincuente = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Byte[] Imagen
        {
            get
            {
                return _Imagen;
            }
            
            set
            {
                base.PropertyModified();
                _Imagen = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveCoordenada
        {
            get
            {
                return _ClaveCoordenada;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveCoordenada = value;                
                
            }
            
        }
                
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            IncidenciaObject newObject;
            IncidenciaObject newOriginalValue;

            newObject = (IncidenciaObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (IncidenciaObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new IncidenciaObject OriginalValue()
        {
            return (IncidenciaObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableIncidenciaObject.HydrateFields(
			System.Int32 Folio,
			System.Nullable<System.Int32> FolioPadre,
			System.String Descripcion,
			System.String Direccion,
			System.String Referencias,
			System.DateTime HoraRecepcion,
			System.Nullable<System.Int32> ClaveEstado,
			System.Nullable<System.Int32> ClaveMunicipio,
			System.Nullable<System.Int32> ClaveLocalidad,
			System.Nullable<System.Int32> ClaveColonia,
			System.Nullable<System.Int32> ClaveCodigoPostal,
			System.String Telefono,
			System.Nullable<System.Int32> ClaveDenunciante,
			System.Int32 ClaveEstatus,
			System.Int32 ClaveUsuario,
			System.Boolean Activo,
			System.Nullable<System.Int32> ClaveTipo,
			System.Nullable<System.Int32> Prioridad,
			System.Nullable<System.DateTime> FechaDocumento,
			System.String NumeroOficio,
			System.Nullable<System.DateTime> FechaSuceso,
			System.String AliasDelincuente,
			System.Byte[] Imagen,
			System.Nullable<System.Int32> ClaveCoordenada)
        {
        _Folio = Folio;
_FolioPadre = FolioPadre;
_Descripcion = Descripcion;
_Direccion = Direccion;
_Referencias = Referencias;
_HoraRecepcion = HoraRecepcion;
_ClaveEstado = ClaveEstado;
_ClaveMunicipio = ClaveMunicipio;
_ClaveLocalidad = ClaveLocalidad;
_ClaveColonia = ClaveColonia;
_ClaveCodigoPostal = ClaveCodigoPostal;
_Telefono = Telefono;
_ClaveDenunciante = ClaveDenunciante;
_ClaveEstatus = ClaveEstatus;
_ClaveUsuario = ClaveUsuario;
_Activo = Activo;
_ClaveTipo = ClaveTipo;
_Prioridad = Prioridad;
_FechaDocumento = FechaDocumento;
_NumeroOficio = NumeroOficio;
_FechaSuceso = FechaSuceso;
_AliasDelincuente = AliasDelincuente;
_Imagen = Imagen;
_ClaveCoordenada = ClaveCoordenada;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableIncidenciaObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[24];
            _myArray[0] = _Folio;
if (_FolioPadre.HasValue) _myArray[1] = _FolioPadre.Value;
_myArray[2] = _Descripcion;
if (!System.String.IsNullOrEmpty(_Direccion)) _myArray[3] = _Direccion;
_myArray[4] = _Referencias;
_myArray[5] = _HoraRecepcion;
if (_ClaveEstado.HasValue) _myArray[6] = _ClaveEstado.Value;
if (_ClaveMunicipio.HasValue) _myArray[7] = _ClaveMunicipio.Value;
if (_ClaveLocalidad.HasValue) _myArray[8] = _ClaveLocalidad.Value;
if (_ClaveColonia.HasValue) _myArray[9] = _ClaveColonia.Value;
if (_ClaveCodigoPostal.HasValue) _myArray[10] = _ClaveCodigoPostal.Value;
if (!System.String.IsNullOrEmpty(_Telefono)) _myArray[11] = _Telefono;
if (_ClaveDenunciante.HasValue) _myArray[12] = _ClaveDenunciante.Value;
_myArray[13] = _ClaveEstatus;
_myArray[14] = _ClaveUsuario;
_myArray[15] = _Activo;
if (_ClaveTipo.HasValue) _myArray[16] = _ClaveTipo.Value;
if (_Prioridad.HasValue) _myArray[17] = _Prioridad.Value;
if (_FechaDocumento.HasValue) _myArray[18] = _FechaDocumento.Value;
if (!System.String.IsNullOrEmpty(_NumeroOficio)) _myArray[19] = _NumeroOficio;
if (_FechaSuceso.HasValue) _myArray[20] = _FechaSuceso.Value;
if (!System.String.IsNullOrEmpty(_AliasDelincuente)) _myArray[21] = _AliasDelincuente;
_myArray[22] = _Imagen;
if (_ClaveCoordenada.HasValue) _myArray[23] = _ClaveCoordenada.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableIncidenciaObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[24];
            _myArray[0] = _Folio;
if (_FolioPadre.HasValue) _myArray[1] = _FolioPadre.Value;
_myArray[2] = _Descripcion;
if (!System.String.IsNullOrEmpty(_Direccion)) _myArray[3] = _Direccion;
_myArray[4] = _Referencias;
_myArray[5] = _HoraRecepcion;
if (_ClaveEstado.HasValue) _myArray[6] = _ClaveEstado.Value;
if (_ClaveMunicipio.HasValue) _myArray[7] = _ClaveMunicipio.Value;
if (_ClaveLocalidad.HasValue) _myArray[8] = _ClaveLocalidad.Value;
if (_ClaveColonia.HasValue) _myArray[9] = _ClaveColonia.Value;
if (_ClaveCodigoPostal.HasValue) _myArray[10] = _ClaveCodigoPostal.Value;
if (!System.String.IsNullOrEmpty(_Telefono)) _myArray[11] = _Telefono;
if (_ClaveDenunciante.HasValue) _myArray[12] = _ClaveDenunciante.Value;
_myArray[13] = _ClaveEstatus;
_myArray[14] = _ClaveUsuario;
_myArray[15] = _Activo;
if (_ClaveTipo.HasValue) _myArray[16] = _ClaveTipo.Value;
if (_Prioridad.HasValue) _myArray[17] = _Prioridad.Value;
if (_FechaDocumento.HasValue) _myArray[18] = _FechaDocumento.Value;
if (!System.String.IsNullOrEmpty(_NumeroOficio)) _myArray[19] = _NumeroOficio;
if (_FechaSuceso.HasValue) _myArray[20] = _FechaSuceso.Value;
if (!System.String.IsNullOrEmpty(_AliasDelincuente)) _myArray[21] = _AliasDelincuente;
_myArray[22] = _Imagen;
if (_ClaveCoordenada.HasValue) _myArray[23] = _ClaveCoordenada.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableIncidenciaObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Folio;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableIncidenciaObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Folio = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            IncidenciaObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Folio};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(IncidenciaObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableIncidenciaObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Folio, 
			System.Nullable<System.Int32> FolioPadre, 
			System.String Descripcion, 
			System.String Direccion, 
			System.String Referencias, 
			System.DateTime HoraRecepcion, 
			System.Nullable<System.Int32> ClaveEstado, 
			System.Nullable<System.Int32> ClaveMunicipio, 
			System.Nullable<System.Int32> ClaveLocalidad, 
			System.Nullable<System.Int32> ClaveColonia, 
			System.Nullable<System.Int32> ClaveCodigoPostal, 
			System.String Telefono, 
			System.Nullable<System.Int32> ClaveDenunciante, 
			System.Int32 ClaveEstatus, 
			System.Int32 ClaveUsuario, 
			System.Boolean Activo, 
			System.Nullable<System.Int32> ClaveTipo, 
			System.Nullable<System.Int32> Prioridad, 
			System.Nullable<System.DateTime> FechaDocumento, 
			System.String NumeroOficio, 
			System.Nullable<System.DateTime> FechaSuceso, 
			System.String AliasDelincuente, 
			System.Byte[] Imagen, 
			System.Nullable<System.Int32> ClaveCoordenada);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class IncidenciaObjectList : ObjectList<IncidenciaObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class IncidenciaObjectListView
        : ObjectListView<Objects.IncidenciaObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public IncidenciaObjectListView(Objects.IncidenciaObjectList list): base(list)
        {
        }
    }
}


