
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 17/08/2009 - 04:24 p.m.
// This is a partial class file. The other one is IncidenciaDependenciaObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class IncidenciaDependenciaObject : BaseObject, IMappeableIncidenciaDependenciaObject, IUniqueIdentifiable, IEquatable<IncidenciaDependenciaObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public IncidenciaDependenciaObject(): base()
        {


        }

        /// <summary>
        /// 
        /// </summary>
        public IncidenciaDependenciaObject(
			System.Int32 ClaveDependencia, System.Int32 Folio): base()
        {

			_ClaveDependencia = ClaveDependencia;
			_Folio = Folio;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public IncidenciaDependenciaObject(
			System.Int32 ClaveDependencia,
			System.Int32 Folio,
			System.Nullable<System.DateTime> FechaNotificacion,
			System.Nullable<System.DateTime> FechaEnvioDependencia): base()
        {

			_ClaveDependencia = ClaveDependencia;
			_Folio = Folio;
			_FechaNotificacion = FechaNotificacion;
			_FechaEnvioDependencia = FechaEnvioDependencia;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveDependencia;
/// <summary>
/// 
/// </summary>
protected System.Int32 _Folio;
/// <summary>
///
/// </summary>
protected System.Nullable<System.DateTime> _FechaNotificacion;
/// <summary>
///
/// </summary>
protected System.Nullable<System.DateTime> _FechaEnvioDependencia;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveDependencia
        {
            get
            {
                return _ClaveDependencia;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveDependencia = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Folio
        {
            get
            {
                return _Folio;
            }
            
            set
            {
                base.PropertyModified();
                _Folio = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaNotificacion
        {
            get
            {
                return _FechaNotificacion;
            }
            
            set
            {
                base.PropertyModified();
                _FechaNotificacion = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaEnvioDependencia
        {
            get
            {
                return _FechaEnvioDependencia;
            }
            
            set
            {
                base.PropertyModified();
                _FechaEnvioDependencia = value;                
                
            }
            
        }
                
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            IncidenciaDependenciaObject newObject;
            IncidenciaDependenciaObject newOriginalValue;

            newObject = (IncidenciaDependenciaObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (IncidenciaDependenciaObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new IncidenciaDependenciaObject OriginalValue()
        {
            return (IncidenciaDependenciaObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableIncidenciaDependenciaObject.HydrateFields(
			System.Int32 ClaveDependencia,
			System.Int32 Folio,
			System.Nullable<System.DateTime> FechaNotificacion,
			System.Nullable<System.DateTime> FechaEnvioDependencia)
        {
        _ClaveDependencia = ClaveDependencia;
_Folio = Folio;
_FechaNotificacion = FechaNotificacion;
_FechaEnvioDependencia = FechaEnvioDependencia;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableIncidenciaDependenciaObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[4];
            _myArray[0] = _ClaveDependencia;
_myArray[1] = _Folio;
if (_FechaNotificacion.HasValue) _myArray[2] = _FechaNotificacion.Value;
if (_FechaEnvioDependencia.HasValue) _myArray[3] = _FechaEnvioDependencia.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableIncidenciaDependenciaObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[6];
            _myArray[0] = _ClaveDependencia;
_myArray[1] = _Folio;
if (_FechaNotificacion.HasValue) _myArray[2] = _FechaNotificacion.Value;
if (_FechaEnvioDependencia.HasValue) _myArray[3] = _FechaEnvioDependencia.Value;
_myArray[4] = this.OriginalValue()._ClaveDependencia;
_myArray[5] = this.OriginalValue()._Folio;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableIncidenciaDependenciaObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[2];
            _myArray[0] = _ClaveDependencia;
_myArray[1] = _Folio;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableIncidenciaDependenciaObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            
        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            IncidenciaDependenciaObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.ClaveDependencia, o.Folio};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(IncidenciaDependenciaObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableIncidenciaDependenciaObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 ClaveDependencia, 
			System.Int32 Folio, 
			System.Nullable<System.DateTime> FechaNotificacion, 
			System.Nullable<System.DateTime> FechaEnvioDependencia);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class IncidenciaDependenciaObjectList : ObjectList<IncidenciaDependenciaObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class IncidenciaDependenciaObjectListView
        : ObjectListView<Objects.IncidenciaDependenciaObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public IncidenciaDependenciaObjectListView(Objects.IncidenciaDependenciaObjectList list): base(list)
        {
        }
    }
}


