
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 12/08/2009 - 06:15 p.m.
// This is a partial class file. The other one is RoboVehiculoAccesoriosObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class RoboVehiculoAccesoriosObject : BaseObject, IMappeableRoboVehiculoAccesoriosObject, IUniqueIdentifiable, IEquatable<RoboVehiculoAccesoriosObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosObject(): base()
        {

			_Clave =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosObject(
			System.Int32 Clave): base()
        {

			_Clave = Clave;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosObject(
			System.Int32 Clave,
			System.Int32 Folio,
			System.Nullable<System.Int32> ClaveVehiculo,
			System.String AccesoriosRobados,
			System.String SePercato,
			System.Nullable<System.DateTime> FechaPercato,
			System.String DescripcionResponsables): base()
        {

			_Clave = Clave;
			_Folio = Folio;
			_ClaveVehiculo = ClaveVehiculo;
			_AccesoriosRobados = AccesoriosRobados;
			_SePercato = SePercato;
			_FechaPercato = FechaPercato;
			_DescripcionResponsables = DescripcionResponsables;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Clave;
/// <summary>
/// 
/// </summary>
protected System.Int32 _Folio;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveVehiculo;
/// <summary>
/// 
/// </summary>
protected System.String _AccesoriosRobados;
/// <summary>
/// 
/// </summary>
protected System.String _SePercato;
/// <summary>
///
/// </summary>
protected System.Nullable<System.DateTime> _FechaPercato;
/// <summary>
/// 
/// </summary>
protected System.String _DescripcionResponsables;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Clave
        {
            get
            {
                return _Clave;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Folio
        {
            get
            {
                return _Folio;
            }
            
            set
            {
                base.PropertyModified();
                _Folio = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveVehiculo
        {
            get
            {
                return _ClaveVehiculo;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveVehiculo = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String AccesoriosRobados
        {
            get
            {
                return _AccesoriosRobados;
            }
            
            set
            {
                base.PropertyModified();
                _AccesoriosRobados = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String SePercato
        {
            get
            {
                return _SePercato;
            }
            
            set
            {
                base.PropertyModified();
                _SePercato = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.DateTime> FechaPercato
        {
            get
            {
                return _FechaPercato;
            }
            
            set
            {
                base.PropertyModified();
                _FechaPercato = value;                
                
            }
            
        }
                
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String DescripcionResponsables
        {
            get
            {
                return _DescripcionResponsables;
            }
            
            set
            {
                base.PropertyModified();
                _DescripcionResponsables = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            RoboVehiculoAccesoriosObject newObject;
            RoboVehiculoAccesoriosObject newOriginalValue;

            newObject = (RoboVehiculoAccesoriosObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (RoboVehiculoAccesoriosObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new RoboVehiculoAccesoriosObject OriginalValue()
        {
            return (RoboVehiculoAccesoriosObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableRoboVehiculoAccesoriosObject.HydrateFields(
			System.Int32 Clave,
			System.Int32 Folio,
			System.Nullable<System.Int32> ClaveVehiculo,
			System.String AccesoriosRobados,
			System.String SePercato,
			System.Nullable<System.DateTime> FechaPercato,
			System.String DescripcionResponsables)
        {
        _Clave = Clave;
_Folio = Folio;
_ClaveVehiculo = ClaveVehiculo;
_AccesoriosRobados = AccesoriosRobados;
_SePercato = SePercato;
_FechaPercato = FechaPercato;
_DescripcionResponsables = DescripcionResponsables;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableRoboVehiculoAccesoriosObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[7];
            _myArray[0] = _Clave;
_myArray[1] = _Folio;
if (_ClaveVehiculo.HasValue) _myArray[2] = _ClaveVehiculo.Value;
_myArray[3] = _AccesoriosRobados;
if (!System.String.IsNullOrEmpty(_SePercato)) _myArray[4] = _SePercato;
if (_FechaPercato.HasValue) _myArray[5] = _FechaPercato.Value;
if (!System.String.IsNullOrEmpty(_DescripcionResponsables)) _myArray[6] = _DescripcionResponsables;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableRoboVehiculoAccesoriosObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[7];
            _myArray[0] = _Clave;
_myArray[1] = _Folio;
if (_ClaveVehiculo.HasValue) _myArray[2] = _ClaveVehiculo.Value;
_myArray[3] = _AccesoriosRobados;
if (!System.String.IsNullOrEmpty(_SePercato)) _myArray[4] = _SePercato;
if (_FechaPercato.HasValue) _myArray[5] = _FechaPercato.Value;
if (!System.String.IsNullOrEmpty(_DescripcionResponsables)) _myArray[6] = _DescripcionResponsables;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableRoboVehiculoAccesoriosObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Clave;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableRoboVehiculoAccesoriosObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Clave = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            RoboVehiculoAccesoriosObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Clave};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(RoboVehiculoAccesoriosObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableRoboVehiculoAccesoriosObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Clave, 
			System.Int32 Folio, 
			System.Nullable<System.Int32> ClaveVehiculo, 
			System.String AccesoriosRobados, 
			System.String SePercato, 
			System.Nullable<System.DateTime> FechaPercato, 
			System.String DescripcionResponsables);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class RoboVehiculoAccesoriosObjectList : ObjectList<RoboVehiculoAccesoriosObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class RoboVehiculoAccesoriosObjectListView
        : ObjectListView<Objects.RoboVehiculoAccesoriosObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public RoboVehiculoAccesoriosObjectListView(Objects.RoboVehiculoAccesoriosObjectList list): base(list)
        {
        }
    }
}


