
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 17/08/2009 - 04:24 p.m.
// This is a partial class file. The other one is TelefonoTelmexObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class TelefonoTelmexObject : BaseObject, IMappeableTelefonoTelmexObject, IUniqueIdentifiable, IEquatable<TelefonoTelmexObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmexObject(): base()
        {

			_Clave =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmexObject(
			System.Int32 Clave): base()
        {

			_Clave = Clave;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmexObject(
			System.Int32 Clave,
			System.String Nombre,
			System.String ApellidoPaterno,
			System.String ApellidoMaterno,
			System.String Direccion,
			System.String Telefono,
			System.Nullable<System.Int32> ClaveCodigoPostal,
			System.Nullable<System.Int32> ClaveMunicipio): base()
        {

			_Clave = Clave;
			_Nombre = Nombre;
			_ApellidoPaterno = ApellidoPaterno;
			_ApellidoMaterno = ApellidoMaterno;
			_Direccion = Direccion;
			_Telefono = Telefono;
			_ClaveCodigoPostal = ClaveCodigoPostal;
			_ClaveMunicipio = ClaveMunicipio;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Clave;
/// <summary>
/// 
/// </summary>
protected System.String _Nombre;
/// <summary>
/// 
/// </summary>
protected System.String _ApellidoPaterno;
/// <summary>
/// 
/// </summary>
protected System.String _ApellidoMaterno;
/// <summary>
/// 
/// </summary>
protected System.String _Direccion;
/// <summary>
/// 
/// </summary>
protected System.String _Telefono;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveCodigoPostal;
/// <summary>
///
/// </summary>
protected System.Nullable<System.Int32> _ClaveMunicipio;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Clave
        {
            get
            {
                return _Clave;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            
            set
            {
                base.PropertyModified();
                _Nombre = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String ApellidoPaterno
        {
            get
            {
                return _ApellidoPaterno;
            }
            
            set
            {
                base.PropertyModified();
                _ApellidoPaterno = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String ApellidoMaterno
        {
            get
            {
                return _ApellidoMaterno;
            }
            
            set
            {
                base.PropertyModified();
                _ApellidoMaterno = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            
            set
            {
                base.PropertyModified();
                _Direccion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            
            set
            {
                base.PropertyModified();
                _Telefono = value;
                
            }
            
        }
        
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveCodigoPostal
        {
            get
            {
                return _ClaveCodigoPostal;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveCodigoPostal = value;                
                
            }
            
        }
                
        /// <summary>
        /// Nullable property
        /// </summary>
        public virtual System.Nullable<System.Int32> ClaveMunicipio
        {
            get
            {
                return _ClaveMunicipio;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveMunicipio = value;                
                
            }
            
        }
                
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            TelefonoTelmexObject newObject;
            TelefonoTelmexObject newOriginalValue;

            newObject = (TelefonoTelmexObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (TelefonoTelmexObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new TelefonoTelmexObject OriginalValue()
        {
            return (TelefonoTelmexObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableTelefonoTelmexObject.HydrateFields(
			System.Int32 Clave,
			System.String Nombre,
			System.String ApellidoPaterno,
			System.String ApellidoMaterno,
			System.String Direccion,
			System.String Telefono,
			System.Nullable<System.Int32> ClaveCodigoPostal,
			System.Nullable<System.Int32> ClaveMunicipio)
        {
        _Clave = Clave;
_Nombre = Nombre;
_ApellidoPaterno = ApellidoPaterno;
_ApellidoMaterno = ApellidoMaterno;
_Direccion = Direccion;
_Telefono = Telefono;
_ClaveCodigoPostal = ClaveCodigoPostal;
_ClaveMunicipio = ClaveMunicipio;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableTelefonoTelmexObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[8];
            _myArray[0] = _Clave;
if (!System.String.IsNullOrEmpty(_Nombre)) _myArray[1] = _Nombre;
if (!System.String.IsNullOrEmpty(_ApellidoPaterno)) _myArray[2] = _ApellidoPaterno;
if (!System.String.IsNullOrEmpty(_ApellidoMaterno)) _myArray[3] = _ApellidoMaterno;
if (!System.String.IsNullOrEmpty(_Direccion)) _myArray[4] = _Direccion;
if (!System.String.IsNullOrEmpty(_Telefono)) _myArray[5] = _Telefono;
if (_ClaveCodigoPostal.HasValue) _myArray[6] = _ClaveCodigoPostal.Value;
if (_ClaveMunicipio.HasValue) _myArray[7] = _ClaveMunicipio.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableTelefonoTelmexObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[8];
            _myArray[0] = _Clave;
if (!System.String.IsNullOrEmpty(_Nombre)) _myArray[1] = _Nombre;
if (!System.String.IsNullOrEmpty(_ApellidoPaterno)) _myArray[2] = _ApellidoPaterno;
if (!System.String.IsNullOrEmpty(_ApellidoMaterno)) _myArray[3] = _ApellidoMaterno;
if (!System.String.IsNullOrEmpty(_Direccion)) _myArray[4] = _Direccion;
if (!System.String.IsNullOrEmpty(_Telefono)) _myArray[5] = _Telefono;
if (_ClaveCodigoPostal.HasValue) _myArray[6] = _ClaveCodigoPostal.Value;
if (_ClaveMunicipio.HasValue) _myArray[7] = _ClaveMunicipio.Value;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableTelefonoTelmexObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Clave;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableTelefonoTelmexObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Clave = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            TelefonoTelmexObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Clave};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(TelefonoTelmexObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableTelefonoTelmexObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Clave, 
			System.String Nombre, 
			System.String ApellidoPaterno, 
			System.String ApellidoMaterno, 
			System.String Direccion, 
			System.String Telefono, 
			System.Nullable<System.Int32> ClaveCodigoPostal, 
			System.Nullable<System.Int32> ClaveMunicipio);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class TelefonoTelmexObjectList : ObjectList<TelefonoTelmexObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class TelefonoTelmexObjectListView
        : ObjectListView<Objects.TelefonoTelmexObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmexObjectListView(Objects.TelefonoTelmexObjectList list): base(list)
        {
        }
    }
}


