
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 04/08/2009 - 06:03 p.m.
// This is a partial class file. The other one is UsuarioCorporacionObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UsuarioCorporacionObject : BaseObject, IMappeableUsuarioCorporacionObject, IUniqueIdentifiable, IEquatable<UsuarioCorporacionObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public UsuarioCorporacionObject(): base()
        {


        }

        /// <summary>
        /// 
        /// </summary>
        public UsuarioCorporacionObject(
			System.Int32 ClaveUsuario, System.Int32 ClaveCorporacion): base()
        {

			_ClaveUsuario = ClaveUsuario;
			_ClaveCorporacion = ClaveCorporacion;

            Initialized();
        }

        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveUsuario;
/// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveCorporacion;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveUsuario
        {
            get
            {
                return _ClaveUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveCorporacion
        {
            get
            {
                return _ClaveCorporacion;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveCorporacion = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            UsuarioCorporacionObject newObject;
            UsuarioCorporacionObject newOriginalValue;

            newObject = (UsuarioCorporacionObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (UsuarioCorporacionObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new UsuarioCorporacionObject OriginalValue()
        {
            return (UsuarioCorporacionObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableUsuarioCorporacionObject.HydrateFields(
			System.Int32 ClaveUsuario,
			System.Int32 ClaveCorporacion)
        {
        _ClaveUsuario = ClaveUsuario;
_ClaveCorporacion = ClaveCorporacion;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableUsuarioCorporacionObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[2];
            _myArray[0] = _ClaveUsuario;
_myArray[1] = _ClaveCorporacion;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableUsuarioCorporacionObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[4];
            _myArray[0] = _ClaveUsuario;
_myArray[1] = _ClaveCorporacion;
_myArray[2] = this.OriginalValue()._ClaveUsuario;
_myArray[3] = this.OriginalValue()._ClaveCorporacion;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableUsuarioCorporacionObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[2];
            _myArray[0] = _ClaveUsuario;
_myArray[1] = _ClaveCorporacion;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableUsuarioCorporacionObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            
        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            UsuarioCorporacionObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.ClaveUsuario, o.ClaveCorporacion};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(UsuarioCorporacionObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableUsuarioCorporacionObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 ClaveUsuario, 
			System.Int32 ClaveCorporacion);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class UsuarioCorporacionObjectList : ObjectList<UsuarioCorporacionObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UsuarioCorporacionObjectListView
        : ObjectListView<Objects.UsuarioCorporacionObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public UsuarioCorporacionObjectListView(Objects.UsuarioCorporacionObjectList list): base(list)
        {
        }
    }
}


