
        
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 09/08/2009 - 10:15 p.m.
// This is a partial class file. The other one is UnidadObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UnidadObject : BaseObject, IMappeableUnidadObject, IUniqueIdentifiable, IEquatable<UnidadObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public UnidadObject(): base()
        {

			_Clave =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public UnidadObject(
			System.Int32 Clave): base()
        {

			_Clave = Clave;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public UnidadObject(
			System.Int32 Clave,
			System.String Codigo,
			System.Int32 ClaveCorporacion,
			System.Boolean Activo): base()
        {

			_Clave = Clave;
			_Codigo = Codigo;
			_ClaveCorporacion = ClaveCorporacion;
			_Activo = Activo;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _Clave;
/// <summary>
/// 
/// </summary>
protected System.String _Codigo;
/// <summary>
/// 
/// </summary>
protected System.Int32 _ClaveCorporacion;
/// <summary>
/// 
/// </summary>
protected System.Boolean _Activo;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Clave
        {
            get
            {
                return _Clave;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            
            set
            {
                base.PropertyModified();
                _Codigo = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 ClaveCorporacion
        {
            get
            {
                return _ClaveCorporacion;
            }
            
            set
            {
                base.PropertyModified();
                _ClaveCorporacion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            
            set
            {
                base.PropertyModified();
                _Activo = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            UnidadObject newObject;
            UnidadObject newOriginalValue;

            newObject = (UnidadObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (UnidadObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new UnidadObject OriginalValue()
        {
            return (UnidadObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableUnidadObject.HydrateFields(
			System.Int32 Clave,
			System.String Codigo,
			System.Int32 ClaveCorporacion,
			System.Boolean Activo)
        {
        _Clave = Clave;
_Codigo = Codigo;
_ClaveCorporacion = ClaveCorporacion;
_Activo = Activo;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableUnidadObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[4];
            _myArray[0] = _Clave;
_myArray[1] = _Codigo;
_myArray[2] = _ClaveCorporacion;
_myArray[3] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableUnidadObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[4];
            _myArray[0] = _Clave;
_myArray[1] = _Codigo;
_myArray[2] = _ClaveCorporacion;
_myArray[3] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableUnidadObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _Clave;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableUnidadObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _Clave = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            UnidadObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.Clave};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(UnidadObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableUnidadObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 Clave, 
			System.String Codigo, 
			System.Int32 ClaveCorporacion, 
			System.Boolean Activo);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class UnidadObjectList : ObjectList<UnidadObject>
    {
    }
}

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class UnidadObjectListView
        : ObjectListView<Objects.UnidadObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public UnidadObjectListView(Objects.UnidadObjectList list): base(list)
        {
        }
    }
}


