
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 17/08/2009 - 04:24 p.m.
// This is a partial class file. The other one is OrganizacionEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Organizacion : Objects.OrganizacionObject, IMappeableOrganizacion, IEquatable<Organizacion>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public Organizacion()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public Organizacion(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public Organizacion(
			System.Int32 Clave,
			System.String Nombre,
			System.String Dirección,
			System.String Telefono,
			System.String Fax,
			System.String Email,
			System.String DireccionWeb,
			System.Int32 ClaveClasificacion)
            : base()
        {

			_Clave = Clave;
			_Nombre = Nombre;
			_Dirección = Dirección;
			_Telefono = Telefono;
			_Fax = Fax;
			_Email = Email;
			_DireccionWeb = DireccionWeb;
			_ClaveClasificacion = ClaveClasificacion;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new Organizacion OriginalValue()
        {
            return (Organizacion)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            Organizacion newObject;            
            

            newObject = (Organizacion)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            Organizacion newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (Organizacion)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableOrganizacion.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableOrganizacion.SetFKValuesForChilds(Organizacion entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(Organizacion other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableOrganizacion
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(Organizacion entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class OrganizacionList : ObjectList<Organizacion>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class OrganizacionListView
        : ObjectListView<Entities.Organizacion>
    {
        /// <summary>
        /// 
        /// </summary>
        public OrganizacionListView(Entities.OrganizacionList list): base(list)
        {
        }
    }
}


