
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 17/08/2009 - 04:24 p.m.
// This is a partial class file. The other one is TelefonoTelmexEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using BSD.C4.Tlaxcala.Sai.Dal.Rules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class TelefonoTelmex : Objects.TelefonoTelmexObject, IMappeableTelefonoTelmex, IEquatable<TelefonoTelmex>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmex()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmex(
			System.Int32 Clave)
            : base()
        {

			_Clave = Clave;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmex(
			System.Int32 Clave,
			System.String Nombre,
			System.String ApellidoPaterno,
			System.String ApellidoMaterno,
			System.String Direccion,
			System.String Telefono,
			System.Nullable<System.Int32> ClaveCodigoPostal,
			System.Nullable<System.Int32> ClaveMunicipio)
            : base()
        {

			_Clave = Clave;
			_Nombre = Nombre;
			_ApellidoPaterno = ApellidoPaterno;
			_ApellidoMaterno = ApellidoMaterno;
			_Direccion = Direccion;
			_Telefono = Telefono;
			_ClaveCodigoPostal = ClaveCodigoPostal;
			_ClaveMunicipio = ClaveMunicipio;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new TelefonoTelmex OriginalValue()
        {
            return (TelefonoTelmex)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            TelefonoTelmex newObject;            
            

            newObject = (TelefonoTelmex)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            TelefonoTelmex newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (TelefonoTelmex)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableTelefonoTelmex.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableTelefonoTelmex.SetFKValuesForChilds(TelefonoTelmex entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(TelefonoTelmex other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableTelefonoTelmex
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(TelefonoTelmex entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class TelefonoTelmexList : ObjectList<TelefonoTelmex>
    {
    }
}
namespace BSD.C4.Tlaxcala.Sai.Dal.Rules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class TelefonoTelmexListView
        : ObjectListView<Entities.TelefonoTelmex>
    {
        /// <summary>
        /// 
        /// </summary>
        public TelefonoTelmexListView(Entities.TelefonoTelmexList list): base(list)
        {
        }
    }
}


